# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 10:48
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171007_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
