# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown',
        ),
    ]
